name: features_shared
description: "Shared features package — auth, profile, notifications."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
  dio: ^5.9.2
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.2.3
  local_auth: ^2.3.0
  package_info_plus: ^10.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

