import 'package:core/core.dart';
import 'package:drift/drift.dart';

import '../../domain/entities/quote_entity.dart';

/// Data-layer model for Quote, bridging API JSON and Drift database rows
/// to the domain [QuoteEntity].
///
/// **Column naming**: The Drift [Quotes] table uses `content` instead of
/// `text` (to avoid shadowing Drift's `text()` builder) and `serverId`
/// instead of `id` (to avoid confusion with auto-generated Drift IDs).
class QuoteModel extends QuoteEntity {
  const QuoteModel({
    required super.localId,
    super.id,
    required super.text,
    required super.author,
    super.source,
    super.isActive,
    super.isSynced,
    super.syncAction,
    super.createdAt,
    super.updatedAt,
  });

  /// Constructs a [QuoteModel] from a JSON map returned by the API.
  ///
  /// Expected shape (from Laravel `QuoteResource`):
  /// ```json
  /// { "id": 1, "text": "...", "author": "...", ... }
  /// ```
  factory QuoteModel.fromJson(Map<String, dynamic> json) {
    return QuoteModel(
      localId: 0, // Will be assigned by SQLite on insert
      id: json['id'] as int?,
      text: json['text'] as String? ?? '',
      author: json['author'] as String? ?? '',
      source: json['source'] as String?,
      isActive: json['is_active'] as bool? ?? true,
      isSynced: true, // Data from server is already synced
      syncAction: null,
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'] as String)
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'] as String)
          : null,
    );
  }

  /// Constructs a [QuoteModel] from a Drift database row.
  ///
  /// The [Quote] class is auto-generated by Drift from the [Quotes] table.
  /// Maps `content` → `text` and `serverId` → `id`.
  factory QuoteModel.fromDatabase(Quote row) {
    return QuoteModel(
      localId: row.localId,
      id: row.serverId,
      text: row.content,
      author: row.author,
      source: row.source,
      isActive: row.isActive,
      isSynced: row.isSynced,
      syncAction: row.syncAction,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    );
  }

  /// Serializes this model to a JSON map for API requests.
  ///
  /// Only includes fields the API expects; excludes local-only
  /// fields like `localId`, `isSynced`, `syncAction`.
  Map<String, dynamic> toJson() {
    return {
      'text': text,
      'author': author,
      if (source != null) 'source': source,
      'is_active': isActive,
    };
  }

  /// Converts this model to a Drift [QuotesCompanion] for database
  /// insert/update operations.
  ///
  /// Maps domain `text` → Drift `content` and `id` → `serverId`.
  QuotesCompanion toDatabaseCompanion() {
    return QuotesCompanion(
      serverId: id != null ? Value(id) : const Value.absent(),
      content: Value(text),
      author: Value(author),
      source: Value(source),
      isActive: Value(isActive),
      isSynced: Value(isSynced),
      syncAction: Value(syncAction),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
    );
  }
}
