import 'package:firebase_core/firebase_core.dart';

/// Service wrapper for Firebase Core initialization.
///
/// Each app flavor (`main`, `variant`) must call [init] with its own
/// [FirebaseOptions] (generated by FlutterFire CLI) before using any
/// Firebase service.
class FirebaseService {
  /// Initializes Firebase with the given [options].
  ///
  /// Must be called once in `bootstrap()` before `runApp()`.
  static Future<void> init({
    required FirebaseOptions options,
  }) async {
    await Firebase.initializeApp(options: options);
  }
}
